ministryofjustice/opg-data-deputy-reporting

terraform/environment/terraform.tfvars.json

Change sirius endpojnt from feature5 to dev
Change sirius endpojnt from feature5 to dev

IN-281 change to dev

---

terraform/environment/alerts.tf

fix alert names

---

terraform/environment/modules/lambda/lambda.tf
terraform/environment/terraform.tfvars.json
terraform/environment/variables.tf

Create Lambda env vars 
Created the env vars
There is no fixed end point for development in digideps land so closest we have is a branch called beth. Not ideal but it will do for now till we sort it out. Also was hesitant over whether to point to pre or master. The manual testing gets done in pre and only the dbs are restored rather than all the docs so I've gone for preprod and the onus is on testers not to send live data.

IN-307 add the env vars for buckets and user needed

---

integration_tests/v2/test_all_routes_errors.py

Tests should pass really
Skipped a couple that are not relevant right now, but we may want to come back to

IN-303 Fixed the integration tests that fail

---

terraform/environment/terraform.tfvars.json

fix inexistant roles

---

lambda_functions/v2/functions/documents/app/api/checklists.py
lambda_functions/v2/functions/documents/app/api/reports.py
lambda_functions/v2/functions/documents/app/api/resources.py
lambda_functions/v2/functions/documents/app/api/supporting_docs.py

Adjust logging level and information exposed

---

terraform/environment/terraform.tfvars.json

fix the bucket name

---

.circleci/config.yml

upgrade to tf 0.13.5

---

.circleci/config.yml

tf init was in the wrong place

---

.github/workflows/scanner.yml

Add an action to scan for packages with manifest and lock files

add scanner action workflow

---

.circleci/config.yml
docs/ci_scripts/login_code_artifact.sh
integration_tests/v2/conftest.py
terraform/environment/provider.tf
terraform/environment/variables.tf

Change sirius CI to integrations-ci

IN-770 change sirius-ci to integrations-ci

---

.circleci/config.yml
terraform/environment/stage.tf

SP-904 - Switch API Gateway TLS to 1.2 #minor

---

.circleci/config.yml

SP-904 - Run the CI pipeline against main not master #patch

---

README.md
docker-compose.yml
lambda_functions/v2/functions/documents/app/api/sirius_service.py
lambda_functions/v2/requirements/dev-requirements.txt
lambda_functions/v2/requirements/requirements.txt
mock_integration_rest_api/requirements.txt

Had to make small changes to PyJWT as package has changed a tiny bit and outputs utf8 by default anyway.
Fixed a few bits here and there
NA

DDPB-4406 update JWT package

---

.github/tag.sh
.github/workflows/live_workflow.yml

Correct failures in release versioning
Edit the syntax properly so that release notes appear based on the PR title and contents of the body block.
NA

DDPB-4031b Fix release versioning

---

.github/workflows/docker_build.yml
.github/workflows/live_workflow.yml
.github/workflows/pr_workflow.yml
lambda_functions/v2/Dockerfile
mock_sirius/Dockerfile
terraform/environment/modules/mock_sirius/ecs.tf

Fix tagging approach
use the branch input to decide whether to tag with main
fix some security issues picked up by trivy
NA

Ddpb 4449c

---

lambda_functions/v2/functions/documents/app/api/helpers.py
lambda_functions/v2/functions/documents/app/api/resources.py
lambda_functions/v2/functions/documents/app/api/sirius_service.py

Wasn't clear what the issue from sirius side was when calls were failing
Expand the logging to assist with this
NA

DDPB-4453 update logging

---

lambda_functions/v2/requirements/requirements.txt

Missed from last pr, and dependabot was failing

DDPB-4696 - bump requests 2.31.0

---

lambda_functions/v2/Dockerfile

Avoid package security vulnerabilities for alpine images

Apk upgrade

---

.github/workflows/docker_build.yml
integration_tests/Dockerfile
integration_tests/requirements.txt
lambda_functions/v2/Dockerfile
lambda_functions/v2/Dockerfile-unittests
lambda_functions/v2/functions/csv-forwarder/Dockerfile
lambda_functions/v2/functions/csv-forwarder/go.mod
lambda_functions/v2/functions/csv-forwarder/go.sum
lambda_functions/v2/requirements/dev-requirements.txt
lambda_functions/v2/requirements/requirements.txt
mock_digideps/Dockerfile
mock_integration_rest_api/Dockerfile
mock_integration_rest_api/requirements.txt
mock_sirius/Dockerfile
mock_sirius_backend/Dockerfile
pact/Dockerfile
pact/requirements.txt

This is a modified version of the renovate updates that work in our setup (we have limitations on connexion).

Renovate Update Patch & Minor Updates

---

.github/workflows/_docker_build.yml

Renovate Update github/codeql-action action to v3

---

mock_sirius/Dockerfile

Update prism to version 15.14.2

Update prism to version 15.14.2

---

mock_sirius/Dockerfile

Added back in the jsonpath upgrade

Added back in the jsonpath upgrade
